export const logos: Record<string, string> = {
  'MetaMask': 'https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg',
  'Coinbase Wallet': 'https://upload.wikimedia.org/wikipedia/commons/2/29/Coinbase_logo.svg',
  'Trust Wallet': 'https://trustwallet.com/assets/images/media/assets/TWT.png',
  'Rabby Wallet': 'https://www.rabby.io/img/logo.svg',
  'Zerion': 'https://assets.coingecko.com/coins/images/8929/small/zerion.png?1678448795',
  'Enkrypt': 'https://enkrypt.com/_nuxt/img/Enkrypt-logo-header.c41428b.png',
  'XDEFI Wallet': 'https://www.xdefi.io/images/XDEFI-logo.svg',
  'Bitget Wallet': 'https://www.bitget.com/favicon.ico',
  'Atomic Wallet': 'https://atomicwallet.io/static/img/atomicwallet_logo_gradient.svg',
  'Brave Wallet': 'https://brave.com/static-assets/images/brave-wallet/brave-wallet-icon.svg',
  'Opera Wallet': 'https://www-static-dev.opera.com/static/images/favicons/favicon-32x32.512994d24a74.png',
  'MathWallet': 'https://www.mathwallet.org/favicon.png',
  'Rainbow Wallet': 'https://rainbow.me/assets/logo.svg',
  'Phantom Wallet': 'https://phantom.app/img/phantom-logo.svg',
};
